language: node_js

node_js: stable

install:
  - npm install  

script:
  - hexo cl       #清除
  - hexo g        #生成
#  - hexo d  

after_script:
  - cd ./public
  - git init
  - git config user.name "fjcgreat" 
  - git config user.email "fjcgreat@outlook.com"
  - git add .
  - git commit -m "update"
  - git push --force "https://${MY_TOKEN}@${GH_REF}" master:master 

branches:
  only:
    - develop
env:
 global:
   - GH_REF: github.com/fjcgreat/fjcgreat.github.io.git